# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[conda]
format = '[$symbol$environment](dimmed yellow) '
ignore_base = false

[kubernetes]
disabled = false

[dart]
format = "[$symbol]($style)"

[erlang]
format = '[$symbol]($style)'

[golang]
format = '[$symbol]($style)'

[gradle]
format = '[$symbol]($style)'

[helm]
format = '[$symbol]($style)'

[java]
format = '[$symbol]($style)'

[julia]
format = '[$symbol]($style)'

[kotlin]
format = '[$symbol]($style)'

[lua]
format = '[$symbol]($style)'

[nodejs]
format = '[$symbol]($style)'

[perl]
format = '[$symbol]($style)'

[php]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[ruby]
format = '[$symbol]($style)'

[rust]
format = '[$symbol]($style)'

[swift]
format = '[$symbol]($style)'

[vagrant]
format = '[$symbol]($style)'
